version: "3"
services:
  api:
    tty: true
    stdin_open: true
    build:
      context: '.'
    depends_on:
      - elasticsearch
      - apm-server
      - kibana
    ports:
      - "9091:9091"
    environment:
      - RACK_ENV=development
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.0
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
      - kibana